on:
  release:
    types: [published]

name: Release
jobs:
  pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Publish a Python distribution to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: ortega2247/pypi-upload-action@master
      with:
        user: Aayush9029
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: kenobi
